version: '3.8'
services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: airbnb
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - 5432:5432
