version: '3.8'
services:
  postgres:
    image: postgres:alpine
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${DB_USER} -d ${DB_NAME}']
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  backend-server:
    image: javokhirm/vention-booking:latest
    container_name: backend-server
    restart: always
    env_file:
      - .env
    ports:
      - 3000:3000
      - 5555:5555
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./logs:/app/logs
