enum ErrorsTypes {
  ACCOMMODATION_FAILED_TO_CREATE = 'ACCOMMODATION_FAILED_TO_CREATE',
  ACCOMMODATION_FAILED_TO_GET_FOR_UPDATING = 'ACCOMMODATION_FAILED_TO_GET_FOR_UPDATING',
  ACCOMMODATION_FAILED_TO_UPDATE = 'ACCOMMODATION_FAILED_TO_UPDATE',
  ACCOMMODATION_FAILED_TO_DELETE = 'ACCOMMODATION_FAILED_TO_DELETE',
  ACCOMMODATION_ADDRESS_FAILED_TO_DELETE = 'ACCOMMODATION_ADDRESS_FAILED_TO_DELETE',
  ACCOMMODATION_FAILED_TO_GET = 'ACCOMMODATION_FAILED_TO_GET',
  AMENITIES_LIST_FAILED_TO_GET = 'AMENITIES_LIST_FAILED_TO_GET',
  AMENITIES_FAILED_TO_GET = 'AMENITIES_FAILED_TO_GET',
  AMENITIES_FAILED_TO_ADD = 'AMENITIES_FAILED_TO_ADD',
  AMENITIES_FAILED_TO_UPDATE = 'AMENITIES_FAILED_TO_UPDATE',
  AMENITIES_FAILED_TO_DELETE = 'AMENITIES_FAILED_TO_DELETE',
  AMENITIES_OWNER_FAILED_TO_VERIFY = 'AMENITIES_OWNER_FAILED_TO_VERIFY',
}

export default ErrorsTypes;
