enum ErrorsTypes {
  ACCOMMODATION_FAILED_TO_CREATE = 'ACCOMMODATION_FAILED_TO_CREATE',
  ACCOMMODATION_NOT_FOUND = 'ACCOMMODATION_NOT_FOUND',
  ACCOMMODATION_NOT_OWNER = 'ACCOMMODATION_NOT_OWNER',
  ACCOMMODATION_CANNOT_DELETE_ADDRESS = 'ACCOMMODATION_CANNOT_DELETE_ADDRESS',
  ACCOMMODATION_NO_FILE_PROVIDED = 'ACCOMMODATION_NO_FILE_PROVIDED',
  ADDRESS_NOT_FOUND = 'ADDRESS_NOT_FOUND',
}

export default ErrorsTypes;
