enum ErrorsTypes {
  PRISMA_NOT_FOUND = 'P2025',
  ACCOMMODATION_FAILED_TO_CREATE = 'ACCOMMODATION_FAILED_TO_CREATE',
  ACCOMMODATION_FAILED_TO_GET_FOR_UPDATING = 'ACCOMMODATION_FAILED_TO_GET_FOR_UPDATING',
  ACCOMMODATION_FAILED_TO_UPDATE = 'ACCOMMODATION_FAILED_TO_UPDATE',
  ACCOMMODATION_FAILED_TO_DELETE = 'ACCOMMODATION_FAILED_TO_DELETE',
  ACCOMMODATION_ADDRESS_FAILED_TO_DELETE = 'ACCOMMODATION_ADDRESS_FAILED_TO_DELETE',
  ACCOMMODATION_FAILED_TO_GET = 'ACCOMMODATION_FAILED_TO_GET',
  AUTH_FAILED_TO_REGISTER = 'AUTH_FAILED_TO_REGISTER',
  AUTH_FAILED_TO_LOGIN = 'AUTH_FAILED_TO_LOGIN',
  AUTH_FAILED_TO_LOGOUT = 'AUTH_FAILED_TO_LOGOUT',
  AUTH_FAILED_TO_REFRESH_TOKENS = 'AUTH_FAILED_TO_REFRESH_TOKENS',
  AUTH_FAILED_TO_UPDATE_EMAIL = 'AUTH_FAILED_TO_UPDATE_EMAIL',
  AUTH_FAILED_TO_VALIDATE = 'AUTH_FAILED_TO_VALIDATE',
  AUTH_FAILED_TO_GET_TOKENS = 'AUTH_FAILED_TO_GET_TOKENS',
  AUTH_FAILED_VERIFY_EMAIL = 'AUTH_FAILED_VERIFY_EMAIL',
  AUTH_FAILED_SEND_VERIFICATION_EMAIL = 'AUTH_FAILED_CANNOT_SEND_VERIFICATION_EMAIL',
  AUTH_FAILED_TOKEN_VERIFY = 'AUTH_FAILED_TOKEN_VERIFY',
}

export default ErrorsTypes;
