// {
//   "wifi": false,
//   "parking": true,
//   "swimmingPool":true,
//   "petAllowance":false,
//   "quiteArea":true,
//   "backyard":true,
//   "smokingAllowance":false,
//   "childFriendly":true,
//   "hospitalNearby":true,
//   "closeToCenter":true,
//   "laundryService":true,
//   "kitchen":true,
//   "airConditioning":true,
//   "tv":false,
//   "airportTransfer":true,
//   "otherAmenities":"",
// }
